# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2.0.3

      - name: Run terraform init
        run: terraform init

      - name: Run terraform plan
        run: terraform plan --no-color --var-file=../Test1Advanced/envs/{inputs.env}/terraform.tfvars

      - name: Run terraform apply
        run: terraform apply --no-color --var-file=../Test1Advanced/envs/{inputs.env}/terraform.tfvars
        env:
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
